#!/bin/sh

while :; do
    case $1 in
        --check-process)
            CHECK_PROCESS=1
            if [ -n "$2" ]; then
                WAIT_PROCESS="$2"
                shift
            else
                [ -z "$WAIT_PROCESS" ] && exit 1
            fi
            shift
            ;;
        --wait-after)
            if [ -n "$2" ]; then
                WAIT_AFTER=$2
                shift
            else
                READ_WAIT_TIME=1
            fi
            shift
            ;;
        *)
            break
            ;;
    esac
done

(( $CHECK_PROCESS )) && { pidof -q "$WAIT_PROCESS" || exit; }

CURRENT_BG_FILE="${CURRENT_BG_FILE-$HOME/.cache/current-desktop-background}"

IFS=
read bgfile
if (( $READ_WAIT_TIME )); then
    read WAIT_AFTER
fi

feh --no-fehbg --bg-fill "$bgfile" || exit 1

[ -n "$CURRENT_BG_FILE" ] && echo "$bgfile" > "$CURRENT_BG_FILE"

if [ -n "$WAIT_AFTER" ]; then
#    echo "Waiting $WAIT_AFTER seconds..."
    if (( $CHECK_PROCESS )); then
        i=1
        while (( $i <= "$WAIT_AFTER" )); do
            pidof -q "$WAIT_PROCESS" || exit
            sleep 1
            i=$(( i + 1 ))
        done
    else
        sleep "$WAIT_AFTER"
    fi
fi

exit 0
