#!/bin/sh

CURRENT_BG_FILE="${CURRENT_BG_FILE-$HOME/.cache/current-desktop-background}"

IFS=
read bgfile

feh --no-fehbg --bg-fill "$bgfile"

[ -n "$CURRENT_BG_FILE" ] && echo "$bgfile" > "$CURRENT_BG_FILE"
